version: '3.7'
services:
    webapp: 
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - MYSQL_USER_NAME=mysql
            - MYSQL_USER_DB=mysql
            - MYSQL_USER_PASS=mysql
        ports:
            - "80:80"
            - "443:443"
            - "3306:3306"
        volumes:
            - type: bind
              source: ./app
              target: /app