version: '3.4'
services:
    webapp: 
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - MYSQL_USER_NAME=mysql_user
            - MYSQL_USER_DB=mysql
            - MYSQL_USER_PASS=808Ya6M2T0SVmoIw
        ports:
            - "80:80"
            - "443:443"
            - "3308:3306"
        volumes:
            - type: bind
              source: ./app
              target: /app